# Generated by Django 5.2.2

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0003_eval_example_and_document_eval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="layout_generation_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="layout_s3_key",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="document",
            name="layout_error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
